spring.datasource.url=jdbc:mariadb://studentapp.cr2qakqeor5f.eu-north-1.rds.amazonaws.com:3306/attendance?useSsl=true&trustServerCertificate=true
spring.datasource.username=admin
spring.datasource.password=11ee22jj33aa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
